driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[desktop]
  - name: steam
    run_list:
      - recipe[desktop::graphics]
      - recipe[desktop::kde]
      - recipe[desktop::steam]
  - name: wine
    run_list:
      - recipe[desktop::graphics]
      - recipe[desktop::kde]
      - recipe[desktop::wine]
