driver:
  name: vagrant
  customize:
    memory: 16384

provisioner:
  name: chef_zero
  product_name: cinc
  product_version: 15.4

platforms:
  - name: ubuntu/bionic64
  - name: debian/buster64

suites:
  - name: kde
    provisioner:
      policyfile: policyfile.rb
      named_run_list: kde
  - name: wine
    provisioner:
      policyfile: policyfile.rb
      named_run_list: wine
  - name: default
    provisioner:
      policyfile: policyfile.rb

