driver:
  name: vagrant
  customize:
    memory: 16384

provisioner:
  name: chef_zero
  product_name: cinc
  product_version: 16.5

# Ubuntu's official 20.04 box crashes VBox on my host.
# Debian's official box seems to work fine.
platforms:
  - name: generic/ubuntu2004
  - name: debian/buster64

suites:
  - name: kde
    provisioner:
      policyfile: Policyfile.rb
      named_run_list: kde
  - name: wine
    provisioner:
      policyfile: Policyfile.rb
      named_run_list: wine
  - name: default
    provisioner:
      policyfile: Policyfile.rb

