name             'desktop'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures desktop'
long_description 'Installs/Configures desktop'
version          '0.1.0'

depends 'apt'
depends 'ark'
depends 'java'
depends 'nodejs'
depends 'ruby_build'
depends 'ruby_rbenv'
